### PR TITLE
Stand in for POJO classes.

### PR DESCRIPTION
**Pull request by maxyu1115**

### CODE REVIEW

**Comment by maxyu1115** [comment]
This commit are stand in for POJO and interfaces to unblock other people working on related things

**Comment by bhavrish** [comment]
Since FilePiece is a POJO, maybe consider putting it in a POJO sub-directory (core/POJO/FilePiece).

**Comment by maxyu1115** [comment]
> Since FilePiece is a POJO, maybe consider putting it in a POJO sub-directory (core/POJO/FilePiece).

So my reasoning was that we aren't expecting a lot of these POJO classes.

**Comment by maxyu1115** [comment]
> Since FilePiece is a POJO, maybe consider putting it in a POJO sub-directory (core/POJO/FilePiece).

Adjusted.

**Review by bhavrish — APPROVED** [review]

**Pull request merged**
